/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.inspire.template.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EmailTemplateEntity service. Represents a row in the &quot;EmailTemplates_EmailTemplateEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.inspire.template.model.impl.EmailTemplateEntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.inspire.template.model.impl.EmailTemplateEntityImpl}.
 * </p>
 *
 * @author Ahmad Taha
 * @see EmailTemplateEntity
 * @see com.liferay.inspire.template.model.impl.EmailTemplateEntityImpl
 * @see com.liferay.inspire.template.model.impl.EmailTemplateEntityModelImpl
 * @generated
 */
public interface EmailTemplateEntityModel extends BaseModel<EmailTemplateEntity> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a email template entity model instance should use the {@link EmailTemplateEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this email template entity.
	 *
	 * @return the primary key of this email template entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this email template entity.
	 *
	 * @param primaryKey the primary key of this email template entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the template ID of this email template entity.
	 *
	 * @return the template ID of this email template entity
	 */
	public long getTemplateId();

	/**
	 * Sets the template ID of this email template entity.
	 *
	 * @param templateId the template ID of this email template entity
	 */
	public void setTemplateId(long templateId);

	/**
	 * Returns the template subject of this email template entity.
	 *
	 * @return the template subject of this email template entity
	 */
	@AutoEscape
	public String getTemplateSubject();

	/**
	 * Sets the template subject of this email template entity.
	 *
	 * @param templateSubject the template subject of this email template entity
	 */
	public void setTemplateSubject(String templateSubject);

	/**
	 * Returns the template body of this email template entity.
	 *
	 * @return the template body of this email template entity
	 */
	@AutoEscape
	public String getTemplateBody();

	/**
	 * Sets the template body of this email template entity.
	 *
	 * @param templateBody the template body of this email template entity
	 */
	public void setTemplateBody(String templateBody);

	/**
	 * Returns the template sender of this email template entity.
	 *
	 * @return the template sender of this email template entity
	 */
	@AutoEscape
	public String getTemplateSender();

	/**
	 * Sets the template sender of this email template entity.
	 *
	 * @param templateSender the template sender of this email template entity
	 */
	public void setTemplateSender(String templateSender);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(EmailTemplateEntity emailTemplateEntity);

	public int hashCode();

	public CacheModel<EmailTemplateEntity> toCacheModel();

	public EmailTemplateEntity toEscapedModel();

	public String toString();

	public String toXmlString();
}