/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.inspire.template.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ScheduleEntity service. Represents a row in the &quot;EmailTemplates_ScheduleEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.inspire.template.model.impl.ScheduleEntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.inspire.template.model.impl.ScheduleEntityImpl}.
 * </p>
 *
 * @author Ahmad Taha
 * @see ScheduleEntity
 * @see com.liferay.inspire.template.model.impl.ScheduleEntityImpl
 * @see com.liferay.inspire.template.model.impl.ScheduleEntityModelImpl
 * @generated
 */
public interface ScheduleEntityModel extends BaseModel<ScheduleEntity> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a schedule entity model instance should use the {@link ScheduleEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this schedule entity.
	 *
	 * @return the primary key of this schedule entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this schedule entity.
	 *
	 * @param primaryKey the primary key of this schedule entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the schedule ID of this schedule entity.
	 *
	 * @return the schedule ID of this schedule entity
	 */
	public long getScheduleId();

	/**
	 * Sets the schedule ID of this schedule entity.
	 *
	 * @param scheduleId the schedule ID of this schedule entity
	 */
	public void setScheduleId(long scheduleId);

	/**
	 * Returns the schedule name of this schedule entity.
	 *
	 * @return the schedule name of this schedule entity
	 */
	@AutoEscape
	public String getScheduleName();

	/**
	 * Sets the schedule name of this schedule entity.
	 *
	 * @param scheduleName the schedule name of this schedule entity
	 */
	public void setScheduleName(String scheduleName);

	/**
	 * Returns the schedule store of this schedule entity.
	 *
	 * @return the schedule store of this schedule entity
	 */
	@AutoEscape
	public String getScheduleStore();

	/**
	 * Sets the schedule store of this schedule entity.
	 *
	 * @param scheduleStore the schedule store of this schedule entity
	 */
	public void setScheduleStore(String scheduleStore);

	/**
	 * Returns the schedule type of this schedule entity.
	 *
	 * @return the schedule type of this schedule entity
	 */
	@AutoEscape
	public String getScheduleType();

	/**
	 * Sets the schedule type of this schedule entity.
	 *
	 * @param scheduleType the schedule type of this schedule entity
	 */
	public void setScheduleType(String scheduleType);

	/**
	 * Returns the schedule flag value of this schedule entity.
	 *
	 * @return the schedule flag value of this schedule entity
	 */
	@AutoEscape
	public String getScheduleFlagValue();

	/**
	 * Sets the schedule flag value of this schedule entity.
	 *
	 * @param scheduleFlagValue the schedule flag value of this schedule entity
	 */
	public void setScheduleFlagValue(String scheduleFlagValue);

	/**
	 * Returns the schedule op of this schedule entity.
	 *
	 * @return the schedule op of this schedule entity
	 */
	@AutoEscape
	public String getScheduleOp();

	/**
	 * Sets the schedule op of this schedule entity.
	 *
	 * @param scheduleOp the schedule op of this schedule entity
	 */
	public void setScheduleOp(String scheduleOp);

	/**
	 * Returns the schedule active of this schedule entity.
	 *
	 * @return the schedule active of this schedule entity
	 */
	public boolean getScheduleActive();

	/**
	 * Returns <code>true</code> if this schedule entity is schedule active.
	 *
	 * @return <code>true</code> if this schedule entity is schedule active; <code>false</code> otherwise
	 */
	public boolean isScheduleActive();

	/**
	 * Sets whether this schedule entity is schedule active.
	 *
	 * @param scheduleActive the schedule active of this schedule entity
	 */
	public void setScheduleActive(boolean scheduleActive);

	/**
	 * Returns the template ID of this schedule entity.
	 *
	 * @return the template ID of this schedule entity
	 */
	public long getTemplateId();

	/**
	 * Sets the template ID of this schedule entity.
	 *
	 * @param templateId the template ID of this schedule entity
	 */
	public void setTemplateId(long templateId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ScheduleEntity scheduleEntity);

	public int hashCode();

	public CacheModel<ScheduleEntity> toCacheModel();

	public ScheduleEntity toEscapedModel();

	public String toString();

	public String toXmlString();
}