/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.inspire.template.model.impl;

import com.liferay.inspire.template.model.EmailTemplateEntity;
import com.liferay.inspire.template.service.EmailTemplateEntityLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EmailTemplateEntity service. Represents a row in the &quot;EmailTemplates_EmailTemplateEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmailTemplateEntityImpl}.
 * </p>
 *
 * @author Ahmad Taha
 * @see EmailTemplateEntityImpl
 * @see com.liferay.inspire.template.model.EmailTemplateEntity
 * @generated
 */
public abstract class EmailTemplateEntityBaseImpl
	extends EmailTemplateEntityModelImpl implements EmailTemplateEntity {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a email template entity model instance should use the {@link EmailTemplateEntity} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			EmailTemplateEntityLocalServiceUtil.addEmailTemplateEntity(this);
		}
		else {
			EmailTemplateEntityLocalServiceUtil.updateEmailTemplateEntity(this);
		}
	}
}